version: "3.9"

services:
  app:
    build: .
    container_name: team-tracket-be
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=db_team-tracket
      - DB_PORT=5432
      - JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ9
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./tmp:/app/tmp

  db:
    image: postgis/postgis:15-3.4
    container_name: team-tracket-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: team-tracket
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_team-tracket"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: team-tracket-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
