version: "3.9"

services:
  app:
    build: .
    container_name: team-tracker-be
    ports:
      - "3005:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=db_team_tracker
      - DB_PORT=5432
      - JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ9
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./tmp:/app/tmp

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: db_team_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  adminer:
    image: adminer
    container_name: team-tracker-adminer
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - db

volumes:
  db_data:
