version: "3.9"

services:
  app:
    build: .
    container_name: realtime-locator-be
    ports:
      - "3005:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=db_realtime_locator
      - DB_PORT=5432
      - JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ9
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./tmp:/app/tmp

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: db_realtime_locator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_realtime_locator"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis

  adminer:
    image: adminer
    container_name: realtime-locator-adminer
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - db

volumes:
  db_data:
